#!/usr/bin/env python3
"""Provision the least-privileged local OpenMRS account used by med-agent-hub."""

from __future__ import annotations

import argparse
import base64
import json
import os
import secrets
import shlex
import stat
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


ROLE_NAME = "Med Agent Hub Patient Reader"
SERVICE_USERNAME = "med-agent-hub"
REQUIRED_PRIVILEGE = "Get Patients"


class OpenMrsClient:
    def __init__(self, base_url: str, username: str, password: str) -> None:
        self.base_url = base_url.rstrip("/")
        token = base64.b64encode(f"{username}:{password}".encode()).decode()
        self.headers = {"Authorization": f"Basic {token}", "Accept": "application/json"}

    def request(self, method: str, path: str, payload: dict[str, Any] | None = None) -> Any:
        data = None
        headers = dict(self.headers)
        if payload is not None:
            data = json.dumps(payload).encode()
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(
            f"{self.base_url}/ws/rest/v1/{path.lstrip('/')}",
            data=data,
            headers=headers,
            method=method,
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                body = response.read()
        except urllib.error.HTTPError as error:
            detail = error.read().decode(errors="replace")
            raise RuntimeError(f"OpenMRS {method} {path} failed: HTTP {error.code}: {detail}") from error
        return json.loads(body) if body else {}

    def exact(self, resource: str, field: str, value: str) -> dict[str, Any] | None:
        query = urllib.parse.urlencode({"q": value, "v": "full", "limit": 100})
        payload = self.request("GET", f"{resource}?{query}")
        match = next(
            (item for item in payload.get("results", []) if item.get(field) == value),
            None,
        )
        if match is not None:
            return match

        # Some OpenMRS REST resources, notably Privilege, silently ignore or do
        # not implement `q`. Page the collection rather than falling back to SQL.
        start = 0
        while True:
            page_query = urllib.parse.urlencode(
                {"v": "full", "limit": 100, "startIndex": start}
            )
            page = self.request("GET", f"{resource}?{page_query}")
            rows = page.get("results", [])
            match = next((item for item in rows if item.get(field) == value), None)
            if match is not None:
                return match
            if len(rows) < 100:
                return None
            start += len(rows)


def _password() -> str:
    return f"Hub{secrets.token_urlsafe(24)}9a"


def _read_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        parsed = shlex.split(value, posix=True)
        values[key] = parsed[0] if parsed else ""
    return values


def _write_env(path: Path, *, base_url: str, username: str, password: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "# Generated by provision-querystore-service-account.py; do not commit.\n"
        f"QUERYSTORE_BASE_URL={shlex.quote(base_url)}\n"
        f"QUERYSTORE_USERNAME={shlex.quote(username)}\n"
        f"QUERYSTORE_PASSWORD={shlex.quote(password)}\n"
    )
    path.write_text(text, encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def _full(client: OpenMrsClient, resource: str, uuid: str) -> dict[str, Any]:
    return client.request("GET", f"{resource}/{uuid}?v=full")


def _effective_privileges(
    client: OpenMrsClient,
    role: dict[str, Any],
    *,
    seen: set[str] | None = None,
) -> set[str]:
    visited = seen if seen is not None else set()
    role_uuid = str(role.get("uuid") or "")
    if role_uuid and role_uuid in visited:
        return set()
    if role_uuid:
        visited.add(role_uuid)
    privileges = {
        str(item.get("name"))
        for item in role.get("privileges", [])
        if item.get("name")
    }
    for inherited in role.get("inheritedRoles", []):
        inherited_uuid = str(inherited.get("uuid") or "")
        if inherited_uuid and inherited_uuid not in visited:
            privileges.update(
                _effective_privileges(
                    client,
                    _full(client, "role", inherited_uuid),
                    seen=visited,
                )
            )
    return privileges


def provision(
    client: OpenMrsClient,
    output: Path,
    *,
    internal_base_url: str,
    service_username: str = SERVICE_USERNAME,
) -> dict[str, str]:
    saved = _read_env(output)
    username = saved.get("QUERYSTORE_USERNAME") or service_username
    password = saved.get("QUERYSTORE_PASSWORD") or _password()

    privilege = client.exact("privilege", "name", REQUIRED_PRIVILEGE)
    if privilege is None:
        raise RuntimeError(f"OpenMRS does not expose required privilege {REQUIRED_PRIVILEGE!r}.")

    role = client.exact("role", "name", ROLE_NAME)
    role_payload = {
        "name": ROLE_NAME,
        "description": "Read-only patient chart access for the local med-agent-hub service.",
        "privileges": [privilege["uuid"]],
        "inheritedRoles": [],
    }
    if role is None:
        role = client.request("POST", "role", role_payload)
    else:
        current = {item.get("name") for item in role.get("privileges", [])}
        inherited = {item.get("uuid") for item in role.get("inheritedRoles", [])}
        if current != {REQUIRED_PRIVILEGE} or inherited:
            client.request("POST", f"role/{role['uuid']}", role_payload)

    user = client.exact("user", "username", username)
    user_payload = {"password": password, "roles": [role["uuid"]]}
    if user is None:
        user = client.request(
            "POST",
            "user",
            {
                "username": username,
                "systemId": username,
                "password": password,
                "person": {
                    "names": [{"givenName": "Med Agent", "familyName": "Hub"}],
                    "gender": "U",
                },
                "roles": [role["uuid"]],
            },
        )
    else:
        assigned = {item.get("uuid") for item in user.get("roles", [])}
        if assigned != {role["uuid"]} or not saved:
            client.request("POST", f"user/{user['uuid']}", user_payload)

    verified_role = _full(client, "role", str(role["uuid"]))
    verified_user = _full(client, "user", str(user["uuid"]))
    effective_privileges = _effective_privileges(client, verified_role)
    assigned_roles = {
        str(item.get("uuid"))
        for item in verified_user.get("roles", [])
        if item.get("uuid")
    }
    if effective_privileges != {REQUIRED_PRIVILEGE} or assigned_roles != {
        str(role["uuid"])
    }:
        raise RuntimeError(
            "Least-privilege verification failed after reconciliation: "
            f"effective_privileges={sorted(effective_privileges)!r}, "
            f"assigned_roles={sorted(assigned_roles)!r}."
        )

    _write_env(
        output,
        base_url=internal_base_url,
        username=username,
        password=password,
    )
    return {
        "username": username,
        "role": ROLE_NAME,
        "privilege": REQUIRED_PRIVILEGE,
        "output": str(output),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--internal-base-url", required=True)
    parser.add_argument("--admin-user", required=True)
    parser.add_argument("--admin-password", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    result = provision(
        OpenMrsClient(args.base_url, args.admin_user, args.admin_password),
        args.output,
        internal_base_url=args.internal_base_url,
    )
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
