#!/usr/bin/env bash
# scripts/snapshot-baseline.sh
# Snapshot the concept-dictionary + openconceptlab state tables from the
# running harness MariaDB into a deterministic SQL file under
#   datasets/sources/ocl/CIEL/<version>/seeded-baseline.sql
#
# Purpose: after a one-time CIEL import (~30-90 min), capture the resulting
# concept tables so that future fresh restarts can `mysql < seeded-baseline.sql`
# in seconds instead of redoing the OCL import.
#
# The dump is INSERT-IGNORE so it cleanly applies on top of the minimal
# Liquibase-seeded concept rows that exist on a fresh OpenMRS schema.
#
# Usage:
#   ./scripts/snapshot-baseline.sh --version v2026-04-28
#   ./scripts/snapshot-baseline.sh --version v2026-04-28 --to PATH   # override output
#
set -euo pipefail
VERSION=""
OUT=""
DB_CONTAINER="${DB_CONTAINER:-harness-openmrs-db}"
DB_USER="${OMRS_DB_USER:-openmrs}"
DB_PASS="${OMRS_DB_PASSWORD:-openmrs}"
DB_NAME="${OMRS_DB_NAME:-openmrs}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --to) OUT="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done
if [[ -z "$VERSION" ]]; then
  echo "Usage: $0 --version <ciel-version>  (e.g. v2026-04-28)" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST_DIR="${ROOT}/targets/validation-harness/datasets/sources/ocl/CIEL/${VERSION}"
mkdir -p "$DEST_DIR"
OUT="${OUT:-$DEST_DIR/seeded-baseline.sql}"

# Concept-dictionary tables (everything that holds CIEL content) + openconceptlab
# state tables (so reloading the snapshot also restores "I have this version imported"
# bookkeeping so the bootstrap is correctly idempotent on next run).
#
# Note: per-table CHARACTER SET / COLLATION declarations are preserved by
# mysqldump's data-only output (CREATE TABLE statements are skipped via
# --no-create-info, but row data is emitted in utf8mb4 via
# --default-character-set=utf8mb4 below). The companion compose stack runs
# MariaDB with `--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci`
# so the loader sees consistent encoding.
# Concept tables that exist in OpenMRS Core 2.8.x / RefApp 3.6.0. Earlier
# Core versions had `concept_word` and `concept_set_derived`; those were
# removed when free-text concept search moved to Lucene. The openconceptlab
# module stores its subscription URL/token in `global_property` rows (key
# prefix `openconceptlab.`) rather than a dedicated table, so we dump those
# global_property rows separately below.
TABLES=(
  concept
  concept_name
  concept_description
  concept_class
  concept_datatype
  concept_map_type
  concept_answer
  concept_set
  concept_reference_source
  concept_reference_term
  concept_reference_map
  concept_reference_term_map
  concept_numeric
  concept_complex
  concept_attribute
  concept_attribute_type
  concept_reference_range
  concept_stop_word
  concept_proposal
  concept_proposal_tag_map
  concept_name_tag
  concept_name_tag_map
  concept_state_conversion
  openconceptlab_import
  openconceptlab_item
)

echo "Snapshotting concept + openconceptlab tables from ${DB_CONTAINER}:${DB_NAME} -> ${OUT}"
echo "Tables: ${#TABLES[@]}"

# Determinism flags:
#   --skip-comments --skip-dump-date  -> no embedded wall clock
#   --skip-add-locks --skip-disable-keys --skip-tz-utc -> stable preamble
#   --extended-insert  (default in mysqldump) keeps the dump compact
#   --insert-ignore   (applies INSERT IGNORE; safe to re-apply on top of partial state)
#   --no-create-info  (tables already exist; we only want data rows)
#   --hex-blob        (binary-safe for byte arrays in some tables)
docker exec "${DB_CONTAINER}" mariadb-dump \
  --user="${DB_USER}" \
  --password="${DB_PASS}" \
  --no-create-info \
  --insert-ignore \
  --extended-insert \
  --hex-blob \
  --skip-comments \
  --skip-dump-date \
  --skip-add-locks \
  --skip-disable-keys \
  --skip-tz-utc \
  --single-transaction \
  --quick \
  --default-character-set=utf8mb4 \
  "${DB_NAME}" \
  "${TABLES[@]}" \
  > "${OUT}"

# Add a deterministic header
HEADER_TMP="$(mktemp)"
{
  echo "-- CIEL v${VERSION} seeded-baseline snapshot"
  echo "-- Generated by scripts/snapshot-baseline.sh"
  echo "-- Tables: ${TABLES[*]}"
  echo "-- Source: ${DB_CONTAINER}:${DB_NAME}"
  echo "--"
  echo "-- Load with:"
  echo "--   ./scripts/load-baseline.sh --version ${VERSION}"
  echo "--"
  echo "SET NAMES utf8mb4;"
  echo "SET FOREIGN_KEY_CHECKS=0;"
  echo ""
} > "$HEADER_TMP"
cat "$HEADER_TMP" "$OUT" > "${OUT}.tmp" && mv "${OUT}.tmp" "$OUT"

# Append openconceptlab global_property rows (subscription URL/token + module
# settings). These persist the "I am pinned to CIEL <vYYYY-MM-DD>" state that
# would otherwise live in a `openconceptlab_subscription` table in older
# Core versions. INSERT IGNORE so reloading on top of a fresh schema does
# not error on duplicate property keys.
docker exec "${DB_CONTAINER}" mariadb \
  --user="${DB_USER}" --password="${DB_PASS}" \
  --default-character-set=utf8mb4 \
  --skip-column-names --batch \
  "${DB_NAME}" \
  -e "SELECT CONCAT('INSERT IGNORE INTO global_property (property, property_value, description, datatype, datatype_config, preferred_handler, handler_config, uuid) VALUES (',
        QUOTE(property), ',', QUOTE(IFNULL(property_value,'')), ',', QUOTE(IFNULL(description,'')), ',',
        IFNULL(QUOTE(datatype),'NULL'), ',', IFNULL(QUOTE(datatype_config),'NULL'), ',',
        IFNULL(QUOTE(preferred_handler),'NULL'), ',', IFNULL(QUOTE(handler_config),'NULL'), ',',
        QUOTE(uuid), ');')
      FROM global_property
      WHERE property LIKE 'openconceptlab.%'
      ORDER BY property;" >> "$OUT"

echo "SET FOREIGN_KEY_CHECKS=1;" >> "$OUT"
rm -f "$HEADER_TMP"

SIZE=$(wc -c < "$OUT" | tr -d ' ')
SHA=$(shasum -a 256 "$OUT" | awk '{print $1}')

# Write companion checksum / provenance
python3 - <<PY > "${DEST_DIR}/seeded-baseline.provenance.json"
import json, datetime
data = {
  "kind": "openmrs-concept-dictionary-snapshot",
  "ciel_version": "${VERSION}",
  "tables": ${#TABLES[@]},
  "local_path": "${OUT}",
  "sha256": "${SHA}",
  "size_bytes": ${SIZE},
  "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
  "source_db": "${DB_CONTAINER}:${DB_NAME}",
  "loader": "scripts/load-baseline.sh --version ${VERSION}",
  "intent": "Fast-path: skip the slow openconceptlab import on fresh restarts by loading this snapshot.",
}
print(json.dumps(data, indent=2))
PY

echo ""
echo "Snapshot complete:"
ls -lh "$OUT"
echo ""
echo "Provenance:"
cat "${DEST_DIR}/seeded-baseline.provenance.json"
